# Feature Engineering 

### *Required modules*

In [1]:
import numpy as np
import pandas as pd 

### *Loading data from folder* 

In [2]:
df = pd.read_csv('E:/Projects/red_wine/Data/Raw/winequality-red.csv')

### *Preview of dataset* 

In [3]:
df.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5  
5      9.4        5  
6      9.4        5  
7     10.0        7  
8      9.5        7  
9     10.5        5

### *Converting label column value into two class "Good and Bad" based on rule*
### *if value < 7 then value = Bad else value = Good*

In [4]:
df['quality'] = df['quality'].apply(lambda x: "Good" if x > 6 else "Bad")

In [5]:
df.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   
5            7.4              0.66         0.00             1.8      0.075   
6            7.9              0.60         0.06             1.6      0.069   
7            7.3              0.65         0.00             1.2      0.065   
8            7.8              0.58         0.02             2.0      0.073   
9            7.5              0.50         0.36             6.1      0.071   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   
5                 13.0                  40.0   0.9978  3.51       0.56   
6                 15.0                  59.0   0.9964  3.30       0.46   
7                 15.0                  21.0   0.9946  3.39       0.47   
8                  9.0                  18.0   0.9968  3.36       0.57   
9                 17.0                 102.0   0.9978  3.35       0.80   

   alcohol quality  
0      9.4     Bad  
1      9.8     Bad  
2      9.8     Bad  
3      9.8     Bad  
4      9.4     Bad  
5      9.4     Bad  
6      9.4     Bad  
7     10.0    Good  
8      9.5    Good  
9     10.5     Bad

### "Checking whether a dataset contains any null values or not" 

In [6]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

### *Checking whether a dataset containse duplicate value or not* 

In [7]:
df.duplicated().sum()

240

In [8]:
df.drop_duplicates(inplace=True, ignore_index = True)

In [9]:
df.duplicated().sum()

0

### *Checking whether a data is balanced data or not*
### *Means checking all label classes having good proportion in dataset*

In [10]:
df['quality'].value_counts()

quality
Bad     1175
Good     184
Name: count, dtype: int64

In [11]:
X = df.drop(['quality'], axis=1)
y = df['quality']

In [12]:
from imblearn.over_sampling import RandomOverSampler

In [13]:
over_sampler = RandomOverSampler(random_state = 42)
X_resampled, y_resampled = over_sampler.fit_resample(X, y)

In [14]:
from collections import Counter

In [15]:
Counter(y_resampled)

Counter({'Bad': 1175, 'Good': 1175})

In [16]:
X_resampled.head(10)

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.66         0.00             1.8      0.075   
5            7.9              0.60         0.06             1.6      0.069   
6            7.3              0.65         0.00             1.2      0.065   
7            7.8              0.58         0.02             2.0      0.073   
8            7.5              0.50         0.36             6.1      0.071   
9            6.7              0.58         0.08             1.8      0.097   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 13.0                  40.0   0.9978  3.51       0.56   
5                 15.0                  59.0   0.9964  3.30       0.46   
6                 15.0                  21.0   0.9946  3.39       0.47   
7                  9.0                  18.0   0.9968  3.36       0.57   
8                 17.0                 102.0   0.9978  3.35       0.80   
9                 15.0                  65.0   0.9959  3.28       0.54   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4  
5      9.4  
6     10.0  
7      9.5  
8     10.5  
9      9.2

In [17]:
X_resampled.shape

(2350, 11)

### *Scaling down data(same-scale)*

In [18]:
from sklearn.preprocessing import MinMaxScaler

In [19]:
scaler = MinMaxScaler()

In [20]:
scaler.fit(X_resampled)

MinMaxScaler()

In [21]:
scaled_data = scaler.transform(X_resampled)

In [22]:
print(scaled_data)

[[0.24778761 0.39726027 0.         ... 0.60629921 0.13772455 0.15384615]
 [0.28318584 0.52054795 0.         ... 0.36220472 0.20958084 0.21538462]
 [0.28318584 0.43835616 0.04       ... 0.40944882 0.19161677 0.21538462]
 ...
 [0.28318584 0.1369863  0.44       ... 0.46456693 0.26946108 0.4       ]
 [0.57522124 0.13013699 0.53       ... 0.22047244 0.2994012  0.38461538]
 [0.47787611 0.13013699 0.47       ... 0.48818898 0.28143713 0.32307692]]


### *Converting label categorical classes into numerical classes* 

In [23]:
y_resampled

0        Bad
1        Bad
2        Bad
3        Bad
4        Bad
        ... 
2345    Good
2346    Good
2347    Good
2348    Good
2349    Good
Name: quality, Length: 2350, dtype: object

In [24]:
y_resampled = y_resampled.apply(lambda x: 1 if x=="Bad" else "0")

In [25]:
y_resampled

0       1
1       1
2       1
3       1
4       1
       ..
2345    0
2346    0
2347    0
2348    0
2349    0
Name: quality, Length: 2350, dtype: object

### *Feature selection* 